config/routes.rb
Rails.application.routes.draw do

  get 'queries/index'

  root to: 'sheets#upload'
  
  resources :sheets, only: [] do
    collection do 
      get :upload
      post :import_service
      post :import_city 
      post :clear  
    end
  end

  resources :queries, only: :index do 
    collection do 
      post :fetch_lawyers
    end
  end
  
end

app/models/enquiry.rb
# created this class, to verify the query functions. 
class Enquiry

  attr_accessor :result 

  def self.joined_location_law_services
    @result ||= Location.joins([lawyers: :services])
  end

  def self.query_1(city_name= 'Chennai', service_name= 'Divorce') 
    city_name.downcase!.strip!
    service_name.downcase!.strip!
    lawyers_on_subject
    @result ||= joined_location_law_services 
    .where('locations.name = ? AND services.name = ? ', city_name, service_name)
  end

  def lawyers_on_subject(queried_service)
    @cool ||= Enquiry.joined_location_law_services
    @cool.where(services: { name: queried_service })
  end 

  def lawyers_on_location_n_service(location, service)
    @result ||= joined_location_law_services
    .where('locations.name = ? AND services.name = ? ', location, service)
  end


end

app/models/lawyer.rb
class Lawyer < ActiveRecord::Base

  belongs_to :location  
 
  has_many :service_lists 
  has_many :services, through: :service_lists
  has_many :payments, through: :service_lists

  delegate :name, to: :location, prefix: true 
  delegate :id, to: :location, prefix: true 

  def self.joined_service_lawyer_location
    @joined_result ||= Service.joins([lawyers: :location], :payments)
  end

  
  def self.based_on_location_service(location_id, service_id)
    joined_service_lawyer_location
    .select('services.name AS SERVICE_NAME, lawyers.code AS LAW_CODE,
      lawyers.name AS LAWYER_NAME,payments.charge as AMOUNT,
      locations.name AS LOCATION_NAME')
    .where('locations.id = ? AND services.id = ?', location_id, service_id).group('lawyers.id')
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :lawyers
  has_many :services, through: :lawyers

  scope :pluck_locations, -> { select('id, name').order(:name) }

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :lawyer
  belongs_to :service_service_list 
end 

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :service_lists
  has_many :payments, through: :service_lists
  has_many :lawyers, through: :service_lists
  
  scope :pluck_services, -> { select('id, name').order(:name) }
end

app/models/service_list.rb
class ServiceList < ActiveRecord::Base
  belongs_to :lawyer
  belongs_to :service
  has_many :payments 
end

app/models/sheet.rb
class Sheet 
  @location_file_path
  @service_file_path 

  class << self
    attr_accessor :location_file_path 
    attr_accessor :service_file_path  
  end
 
  def self.upload_location_and_lawyers
    return false unless location_and_lawyer_blank? 
    get_locations
    get_lawyers
    link_location_lawyer
    true
  end

  def self.location_and_lawyer_blank?
    Lawyer.all.blank? && Location.all.blank?
  end

  def self.upload_services
    return false unless Service.all.blank?
    get_services
    link_payment_lawyer_service
    true
  end 

  def self.raw_location_lawyers
    @raw ||= Roo::CSV.new(location_file_path)
  end

  def self.raw_services
    @raw ||= Roo::CSV.new(service_file_path)
  end

  def self.load_locations
    locations = []
    raw_location_lawyers.each do |code, name, experience, location, rating|
      location.downcase!
      location.strip!
      locations.push location
    end

    locations.shift
    locations.uniq!
    locations.sort!
  end
 
  def self.load_lawyers
    lawyers = []
    raw_location_lawyers.each do |code, name, experience, location, rating|
      lawyer  = { 
        code: code.try(:strip), 
        name: name.try(:strip).try(:downcase),
        experience: experience.try(:to_i), 
        rating: rating.try(:to_f) 
      }
      lawyers.push(lawyer)
    end

    lawyers.shift
    lawyers
  end

  def self.load_services
    services = []
    raw_services.each do |law_code, service_code, service_name, charge|
      service_code.try(:strip!)
      service_name.try(:strip!).try(:downcase!)

      service = {
        code: service_code,
        name: service_name
      }
      services.push(service)
    end

    puts services.inspect 
    puts "before shift size is #{services.size}"
    services.shift
    services.uniq! 
    puts "after uniq! size is #{services.size}"
    services
  end
 

  def self.get_locations 
    load_locations.map { |location|
      Location.create(name: location)
    }
  end

  def self.get_lawyers
    load_lawyers.map { |lawyer|
      Lawyer.create(lawyer)
    }
  end

  def self.get_services 
    load_services.map { |service| 
      Service.create(service)
    }
  end

  def self.link_location_lawyer
    raw_location_lawyers.each do |code, name, experience, location, rating|
      lawyer = Lawyer.where(code: code).first 
      location = Location.where(name: location).first 
      lawyer.update_attributes(location_id: location.id) if location.present? 
    end
  end

  def self.link_payment_lawyer_service
    raw_services.each do |law_code, service_code, service_name, charge|
      service = Service.where(code: service_code.strip).first 
      lawyer = Lawyer.where(code: law_code.strip).first 
      if (service.present? && lawyer.present?)
        s = ServiceList.create(lawyer_id: lawyer.id, service_id: service.id)
        Payment.create(service_list_id: s.id, charge: charge.try(:to_f)) 
      end
    end
  end

  def self.clear_all
    Lawyer.delete_all
    Location.delete_all 
    Payment.delete_all
    Service.delete_all 
    ServiceList.delete_all 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  before_action :get_services, only: :index
  before_action :get_locations, only: :index 

  def index
  end

  def fetch_lawyers
    location_id = params[:location_id] 
    service_id = params[:service_id]
    @eligible_lawyers = Lawyer.based_on_location_service(location_id, service_id)
  end


  private
  def get_services
    @service_list = Service.pluck_services
    if @service_list.blank?
      flash[:error] = "Please import records before you query."
      redirect_to root_path 
    end

  end

  def get_locations
    @location_list = Location.pluck_locations
    if @location_list.blank? 
      flash[:error] = "Please import records before you query."
      redirect_to root_path
    end
  end

  
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  
  before_action :get_file, only: [:import_city, :import_service]

  def upload
  end

  def import_city 

    if @file.present? 
      Sheet.location_file_path = @file 
      @status = Sheet.upload_location_and_lawyers
    end
  end

  def import_service
    if @file.present? 
      Sheet.service_file_path = @file 
      @status = Sheet.upload_services
    end
  end

  def clear
    Sheet.clear_all
    flash[:success] = "Cleared all data."
    redirect_to root_path
  end


  private
  def get_file
    @file = params[:file].path if params[:file].present? 
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CustApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/queries/_filtered_result.html.erb
<table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>service name</th>
        <th>lawyer code</th>
        <th>lawyer name </th>
        <th>location</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @eligible_lawyers.each do |result| %>
        <tr>
          <td><%= result.SERVICE_NAME %></td>
          <td><%= result.LAW_CODE %></td>
          <td><%= result.LAWYER_NAME %></td>
          <td><%= result.LOCATION_NAME  %></td> 
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/queries/fetch_lawyers.js.erb
<% if @eligible_lawyers.present? %> 
  $("#filtered_result").html("<%= escape_javascript( render(partial: "filtered_result")) %>");
<% else %> 
  $('#filtered_result').html("No eligible Lawyers found.");
<% end %> 

app/views/queries/index.html.erb
<%= link_to 'Home', root_path %> 
 

<%= form_tag(fetch_lawyers_queries_path, method: :post, remote: true, 
  id: 'search_form', authenticity_token: true) do %>

  <div class = "form-element">
    <%= label_tag :location, "Select a location: " %> 
  <%= select_tag :location_id, options_from_collection_for_select(@location_list, :id, :name) %>
  
  </div>

  <div class="form-element">
    <%= label_tag :service, 'Select a Service :' %> 
  <%= select_tag :service_id, options_from_collection_for_select(@service_list, :id, :name)  %>

  </div>

  <div class="form-element submit-div">
    <%= submit_tag "Query", class: 'success-button', remote: true %>
  </div>  

<% end %>
  

  <div id="filtered_result">
    <% if @eligible_lawyers.present? %> 
    <%= render 'filtered_result' %> 
    <% end %> 
 </div> 

app/views/sheets/_city_upload.html.erb
<h3> Upload City </h3>
<span id='city'> <%= render 'flash' %>  </span>
  
<div id="upload_city">
  <%= form_tag(import_city_sheets_path, method: :post, multipart: true, 
    remote: true, authenticity_token: true) do %>
    <%= file_field_tag :file, class: 'file-field' %>
    <%= submit_tag "Import City List", class: 'success-button', remote: true %>
  <% end %>
</div>

app/views/sheets/_flash.html.erb
<h5></h5>

app/views/sheets/_service_upload.html.erb
<h3> Upload Services </h3>
<span id='service'> <%= render 'flash' %> </span>

<div id="upload_service">
  <%= form_tag(import_service_sheets_path, method: :post, multipart: true, 
    remote: true, authenticity_token: true) do %>
    <%= file_field_tag :file, class: 'file-field' %>
    <%= submit_tag "Import Service List", class: 'success-button', remote: true  %>
  <% end %>
</div>

app/views/sheets/import_city.js.erb
<% if @file %>
  <% if @status %>  
    $("#city h5").text("successfully uploaded city & lawyer info.");
    $('#city h5').removeClass().addClass('success');
  
  <% else %> 
    $("#city h5").text("Sorry, city & lawyer list is already uploaded.");
    $('#city h5').removeClass().addClass('error');
  <% end %> 

<% else %>

  $("#city h5").text("Sorry, No file found. ");
  $('#city h5').removeClass().addClass('error'); 
<% end %> 



App.unBlockUI($('#upload_city'));

app/views/sheets/import_service.js.erb
<% if @file %>
  <% if @status %>  
    $("#service h5").text("successfully uploaded Service List.");
    $('#service h5').removeClass().addClass('success');
  
  <% else %> 
    $("#service h5").text("Sorry, Service list is already uploaded.");
    $('#service h5').removeClass().addClass('error');
  <% end %> 

<% else %>
  $("#service h5").text("Sorry, No file found. ");
  $('#service h5').removeClass().addClass('error'); 
<% end %> 


App.unBlockUI($('#upload_service'));

app/views/sheets/upload.html.erb
<%= link_to 'Clear Data', clear_sheets_path, method: :post, 
  data: {confirm: "Are you sure to clear all data ? "} %> 

<div id="success"> <%= flash[:success] %>  </div>
<div id="error"> <%= flash[:error] %>  </div>


<div id="upload_page">

   <%= render 'city_upload' %>

   <%= render 'service_upload' %> 
   

</div>


<div id="query_db">
  <%= link_to 'Query Access', queries_path, class: 'success-button', id: 'query_button' %> 
</div>